export const TAG_DUMMY_DATA = [
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2417577,
    name: 'javascript',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2013187,
    name: 'python',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1862535,
    name: 'java',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1555591,
    name: 'c#',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1444169,
    name: 'php',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1384280,
    name: 'android',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1142982,
    name: 'html',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1029170,
    name: 'jquery',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 774665,
    name: 'c++',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 769422,
    name: 'css',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 674097,
    name: 'ios',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 650447,
    name: 'mysql',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 640820,
    name: 'sql',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 461518,
    name: 'r',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 440599,
    name: 'node.js',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 410319,
    name: 'reactjs',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 397255,
    name: 'arrays',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 384259,
    name: 'c',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 369783,
    name: 'asp.net',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 344987,
    name: 'json',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 333776,
    name: 'ruby-on-rails',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 322541,
    name: '.net',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 322134,
    name: 'sql-server',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 321292,
    name: 'python-3.x',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 317709,
    name: 'swift',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 296121,
    name: 'django',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 292484,
    name: 'objective-c',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 283247,
    name: 'angular',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 268328,
    name: 'excel',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 262552,
    name: 'angularjs',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 257013,
    name: 'pandas',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 252205,
    name: 'regex',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 225422,
    name: 'ruby',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 221481,
    name: 'iphone',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 220449,
    name: 'ajax',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 218899,
    name: 'linux',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 209815,
    name: 'xml',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 202590,
    name: 'vba',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 199495,
    name: 'spring',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 198727,
    name: 'asp.net-mvc',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 196702,
    name: 'laravel',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 193047,
    name: 'typescript',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 188801,
    name: 'database',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 185886,
    name: 'wordpress',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 177324,
    name: 'string',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 166404,
    name: 'wpf',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 165832,
    name: 'mongodb',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 159543,
    name: 'windows',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 158921,
    name: 'postgresql',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 156068,
    name: 'xcode',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 147626,
    name: 'bash',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 144462,
    name: 'oracle',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 143665,
    name: 'git',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 140527,
    name: 'amazon-web-services',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 138039,
    name: 'flutter',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 137869,
    name: 'vb.net',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 135923,
    name: 'multithreading',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 132996,
    name: 'list',
  },
  {
    collectives: [
      {
        tags: [
          'firebase-test-lab',
          'google-cloud-shell',
          'google-cloud-profiler',
          'google-app-engine-launch',
          'firebase-app-indexing',
          'google-cloud-composer',
          'google-cloud-translate',
          'google-anthos',
          'google-cloud-identity',
          'google-cloud-endpoints',
          'google-cloud-automl-nl',
          'google-cloud-deploy',
          'google-cloud-data-fusion',
          'google-cloud-save',
          'google-cloud-ml',
          'google-cloud-logging',
          'firebase-dynamic-links',
          'google-cloud-billing',
          'nativescript-firebase',
          'firebase-security',
          'bigtable',
          'firebase-job-dispatcher',
          'google-cloud-iot',
          'google-cloud-vertex-ai',
          'google-cloud-cdn',
          'google-cloud-interconnect',
          'google-cloud-datastore',
          'google-cloud-pubsub',
          'google-kubernetes-engine',
          'google-cloud-pubsublite',
          'google-cloud-intellij',
          'stackdriver',
          'google-cloud-visualstudio',
          'google-cloud-recommendation',
          'firebase-queue',
          'google-cloud-vision',
          'google-cloud-memorystore',
          'google-fusion-tables',
          'google-cloud-ops-agent',
          'recaptcha-enterprise',
          'google-cloud-transcoder',
          'google-data-studio',
          'google-cloud-talent-solution',
          'google-cloud-bigtable',
          'google-migrate-for-compute-engine',
          'firebase-admin',
          'google-prediction',
          'firebase-hosting',
          'google-cloud-language',
          'google-cloud-cpp',
          'firebase-in-app-messaging',
          'google-cloud-debugger',
          'google-cloud-sdk',
          'dialogflow-cx',
          'google-cloud-filestore',
          'dialogflow-es-fulfillment',
          'firebase-admob',
          'google-cloud-spanner',
          'google-dataflow',
          'google-cloud-robotics',
          'google-cloud-dataflow',
          'google-cloud-load-balancer',
          'google-cloud-build',
          'google-app-engine-golang',
          'google-cloud-scheduler',
          'firebase-invites',
          'firebase-machine-learning',
          'firebase-mlkit',
          'google-cloud-tools',
          'firebase',
          'google-cloud-source-repos',
          'google-cloud-tpu',
          'google-cloud-sql',
          'react-native-firebase',
          'google-cloud-test-lab',
          'google-bigquery',
          'google-cloud-dataproc-metastore',
          'dialogflow-es',
          'google-container-optimized-os',
          'google-cloud-data-transfer',
          'google-cloud-iam',
          'google-cloud-asset-inventory',
          'google-cloud-webrisk',
          'google-cloud-http-load-balancer',
          'google-cloud-dataproc',
          'google-app-engine-python',
          'google-cloud-shell-editor',
          'firebaseui',
          'google-cloud-url-maps',
          'google-translate',
          'google-cloud-console',
          'firebase-cloud-functions',
          'google-cloud-armor',
          'google-cloud-error-reporting',
          'firebase-notifications',
          'google-cloud-python',
          'google-cloud-speech',
          'google-cloud-datalab',
          'google-cloud-print',
          'redux-saga-firebase',
          'google-cloud-instances',
          'google-cloud-network-load-balancer',
          'google-cloud-messaging',
          'firebase-console',
          'google-cloud-internal-load-balancer',
          'apigee',
          'google-cloud-powershell',
          'google-app-engine',
          'cordova-plugin-firebasex',
          'firebase-predictions',
          'google-cloud-node',
          'firebase-ab-testing',
          'jib',
          'google-container-registry',
          'firebase-app-check',
          'google-cloud-nl',
          'firebase-database',
          'google-container-os',
          'google-cloud-repository',
          'google-cloud-dns',
          'google-cloud-php-client',
          'google-cloud-networking',
          'google-cloud-stackdriver',
          'cloud-document-ai',
          'react-redux-firebase',
          'google-cloud-router',
          'firebase-realtime-database',
          'google-cloud-run',
          'google-cloud-endpoints-v2',
          'google-cloud-proxy',
          'firebase-cli',
          'firebase-assistant',
          'apigee-baas',
          'google-cloud-marketplace',
          'firebase-crash-reporting',
          'gcloud',
          'google-cloud-identity-aware-proxy',
          'firebase-performance',
          'firebase-polymer',
          'firebase-extensions',
          'google-cloud-spanner-emulator',
          'firebase-authentication',
          'google-cloud-dataprep',
          'google-container-builder',
          'google-analytics-firebase',
          'maven-jib',
          'firebase-cloud-messaging',
          'firebase-app-distribution',
          'google-cloud-kms',
          'google-cloud-vpn',
          'google-cloud-firestore',
          'google-cloud-automl',
          'firebase-tools',
          'google-cloud-search',
          'firebase-util',
          'google-cloud-trace',
          'google-cloud-resource-manager',
          'google-cloud-print-privet',
          'firebase-analytics',
          'google-cloud-storage-r',
          'google-app-engine-php',
          'google-app-engine-patch',
          'google-app-engine-deploy',
          'google-cloud-functions',
          'google-cloud-ai',
          'google-cloud-instance-template',
          'google-cloud-launcher',
          'google-cloud-tasks',
          'google-cloud-code',
          'google-cloud-monitoring',
          'google-app-engine-go',
          'google-cloud-metrics',
          'firebase-remote-config',
          'firebasesimplelogin',
          'google-cloud-api-gateway',
          'rest-firebase',
          'google-cloud-storage',
          'google-cloud-ml-engine',
          'google-cloud-registry',
          'firebase-storage',
          'google-cloud-ai-platform-pipelines',
          'google-compute-engine',
          'google-cloud-dlp',
          'google-cloud-platform',
          'google-cloud-healthcare',
        ],
        external_links: [
          {
            type: 'website',
            link: 'https://cloud.google.com/developers',
          },
          {
            type: 'support',
            link: 'https://googlecloud-community.slack.com/',
          },
          {
            type: 'twitter',
            link: 'https://twitter.com/googlecloudtech',
          },
          {
            type: 'facebook',
            link: 'https://facebook.com/googlecloud',
          },
          {
            type: 'instagram',
            link: 'https://instagram.com/googlecloud',
          },
        ],
        description:
          'Google Cloud provides organizations with leading infrastructure, platform capabilities and industry solutions to help them solve their most critical business problems.',
        link: '/collectives/google-cloud',
        name: 'Google Cloud',
        slug: 'google-cloud',
      },
    ],
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 131236,
    name: 'firebase',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 127068,
    name: 'spring-boot',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 126966,
    name: 'dataframe',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 123945,
    name: 'eclipse',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 122401,
    name: 'azure',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 120918,
    name: 'react-native',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 119316,
    name: 'docker',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 115700,
    name: 'algorithm',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 112912,
    name: 'macos',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 111078,
    name: 'forms',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 110574,
    name: 'image',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 110541,
    name: 'visual-studio',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 109473,
    name: 'scala',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 106150,
    name: 'powershell',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 105235,
    name: 'numpy',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 104873,
    name: 'function',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 102645,
    name: 'api',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 102541,
    name: 'twitter-bootstrap',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 99395,
    name: 'selenium',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 98176,
    name: 'performance',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 96735,
    name: 'vue.js',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 96176,
    name: 'winforms',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 95195,
    name: 'python-2.7',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 93349,
    name: 'matlab',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 92383,
    name: 'sqlite',
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 91752,
    name: 'hibernate',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 91321,
    name: 'apache',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 91144,
    name: 'loops',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 89797,
    name: 'rest',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 89704,
    name: 'entity-framework',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 88911,
    name: 'shell',
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 88110,
    name: 'express',
  },
];
